### ISSUE TITLE
Hello,麻烦问一下服务器端为什么选择go语言呢？

### ISSUE THREAD

**Issue by yzhfd** [GoBelieveIO/im_service#18]
您好，
       我一直在研究IM服务端开发这块，我看有一些人选择了C++进行开发，麻烦问一下你们为啥选择了go语言呢？请问一下除了这个选择之外，还有别的语言或者框架推荐一下的吗？谢谢

**Comment by richmonkey** [comment]
go 并发开发简单，同时效率还不错。感觉这种问题应该不应该在这里问。谢谢！
