### ISSUE TITLE
自己搭建服务器如何设置推送证书

### ISSUE THREAD

**Issue by 501Miles** [GoBelieveIO/im_service#23]
使用源码在自己服务器上搭建im_service后，如何设置以下参数，如何设置ios推送

**Comment by 501Miles** [comment]
![qq20180723-154216](https://user-images.githubusercontent.com/17874085/43063637-fd697cba-8e8e-11e8-80f6-89a9893aca2c.png)

**Comment by richmonkey** [comment]
imservice没有推送apns的功能
