### ISSUE TITLE
RestAPI接口在哪个服务里

### ISSUE THREAD

**Issue by wiiiky** [GoBelieveIO/im_service#24]
编译并执行了im、ims、imr三个服务，配置也根据自己的情况做了修改，日志里没有报错。但我不知道服务端的RestAPI接口在哪里。
http://developer.gobelieve.io/static/docs/im/Server.html

我在源代码里没有找到相应的代码，麻烦指点一下。

**Comment by richmonkey** [comment]
api不是im的核心组件，只是平台的一部分，所以没有开源
