### ISSUE TITLE
mysqldb_appsource non exist

### ISSUE THREAD

**Issue by py-samsung** [GoBelieveIO/im_service#3]
1.im.cfg.sample 里没有相关的配置项
2.make 出来的应用没有im_api 与readme 文档对应不上

**Comment by yu000hong** [comment]
同样的问题
1. mysqldb_appsource non exist
2. 缺少im_api

**Comment by richmonkey** [comment]
mysqldb_appsource修改成可选配置

**Comment by richmonkey** [comment]
im_api已经从工程中删除
