### ISSUE TITLE
最新的 Readme 是不是编译步骤漏掉了？

### ISSUE THREAD

**Issue by veryitman** [GoBelieveIO/im_service#30]
按照之前版本的 Readme 来编译会报错，最后通过执行 `dep ensure` 再 `make install` 就可以了。
现在按照最新的 Readme 来编译，执行 `make install` 还是报错，不知道什么原因？

`
cd im && make
go build -ldflags "-X main.VERSION=2.0.0 -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`' -X 'main.GIT_COMMIT_ID=`git log --pretty=format:"%h" -1`' -X 'main.GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`'" im.go subscriber.go connection.go client.go peer_client.go group_client.go room_client.go customer_client.go route.go app_route.go protocol.go message.go group_manager.go group.go set.go config.go monitoring.go sio.go storage_rpc.go channel.go storage_message.go route_message.go user.go rpc.go dummy_grpc.go device.go group_message_deliver.go
command-line-arguments
./sio.go:93:28: undefined: engineio.MessageBinary
./sio.go:117:10: undefined: engineio.MessageText
make[1]: *** [im] Error 2
make: *** [im_bin] Error 2
`

**Comment by richmonkey** [comment]
把GOPATH目录清空， 然后把imservice目录下的vendor目录清空，之后再重新安装依赖 dep ensure

**Comment by veryitman** [comment]
Thanks @richmonkey
