### ISSUE TITLE
依赖的包文件没有实现的方法

### ISSUE THREAD

**Issue by heliosun** [GoBelieveIO/im_service#33]
google.golang.org/grpc/internal/transport
../../google.golang.org/grpc/internal/transport/handler_server.go:221:12: undefined: http2.TrailerPrefix
../../google.golang.org/grpc/internal/transport/http2_client.go:632:20: f.Size undefined (type hpack.HeaderField has no field or method Size)
../../google.golang.org/grpc/internal/transport/http2_client.go:1138:45: undefined: http2.MetaHeadersFrame
../../google.golang.org/grpc/internal/transport/http2_client.go:1251:24: t.framer.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)
../../google.golang.org/grpc/internal/transport/http2_client.go:1262:9: undefined: http2.MetaHeadersFrame
../../google.golang.org/grpc/internal/transport/http2_server.go:287:45: undefined: http2.MetaHeadersFrame
../../google.golang.org/grpc/internal/transport/http2_server.go:460:9: undefined: http2.MetaHeadersFrame
../../google.golang.org/grpc/internal/transport/http2_server.go:731:19: f.Size undefined (type hpack.HeaderField has no field or method Size)
../../google.golang.org/grpc/internal/transport/http_util.go:262:43: undefined: http2.MetaHeadersFrame
../../google.golang.org/grpc/internal/transport/http_util.go:672:6: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
../../google.golang.org/grpc/internal/transport/http_util.go:672:6: too many errors

**Comment by richmonkey** [comment]
使用make 编译
