### ISSUE TITLE
gRPC.go编译错误

### ISSUE THREAD

**Issue by zhubaoskyover** [GoBelieveIO/im_service#35]
func (s *RPCServer) LoadHistoryMessage(ctx context.Context, r *pb.LoadHistoryRequest) (*pb.HistoryMessage, error) {
	appid := r.Appid
	uid := r.Uid
	msgid := r.LastId
	
	storage_pool := GetStorageConnPool(uid)
GetStorageConnPool无实现函数

**Comment by richmonkey** [comment]
使用 make 编译

**Comment by zhubaoskyover** [comment]
谢谢！
