### ISSUE TITLE
make install sio.go:93:28: undefined: engineio.MessageBinary

### ISSUE THREAD

**Issue by magix** [GoBelieveIO/im_service#36]
make install
cd im && make
make[1]: Entering directory `/root/go/im_service/im'
go build -ldflags "-X main.VERSION=2.0.0 -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`' -X 'main.GIT_COMMIT_ID=`git log --pretty=format:"%h" -1`' -X 'main.GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`'" -o im im_server.go im.go subscriber.go connection.go client.go peer_client.go group_client.go room_client.go customer_client.go route.go app_route.go protocol.go message.go group_manager.go group.go set.go config.go monitoring.go sio.go storage_rpc.go channel.go storage_message.go route_message.go user.go rpc.go dummy_grpc.go device.go group_message_deliver.go relationship.go relationship_pool.go redis_channel.go
# command-line-arguments
./sio.go:93:28: undefined: engineio.MessageBinary
./sio.go:117:10: undefined: engineio.MessageText
make[1]: *** [im] Error 2
make[1]: Leaving directory `/root/go/im_service/im'

go version go1.13 linux/amd64

what`s the problem ? buddy

**Comment by richmonkey** [comment]
clean engineio package under $GOPATH, 
dep ensure  to install all depencies to vender
