### ISSUE TITLE
我执行 make install 报错

### ISSUE THREAD

**Issue by objectZhang** [GoBelieveIO/im_service#44]
我在墙内，没办法通过 dep ensure 解决依赖，我将所有的依赖包都从github下载到了本地，但是在执行 make install 的时候报错。 报错如下：

make install
cd im && make
make[1]: 进入目录“/usr/local/golang/src/github.com/GoBelieveIO/im_service/im”
go build -ldflags "-X main.VERSION=2.0.0 -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`' -X 'main.GIT_COMMIT_ID=`git log --pretty=format:"%h" -1`' -X 'main.GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`'" -o im im_server.go im.go subscriber.go connection.go client.go peer_client.go group_client.go room_client.go customer_client.go route.go app_route.go protocol.go message.go group_manager.go group.go set.go config.go monitoring.go sio.go storage_rpc.go channel.go storage_message.go route_message.go user.go rpc.go dummy_grpc.go device.go group_message_deliver.go relationship.go relationship_pool.go
# command-line-arguments
./sio.go:93:28: undefined: engineio.MessageBinary
./sio.go:117:10: undefined: engineio.MessageText
make[1]: *** [im] 错误 2
make[1]: 离开目录“/usr/local/golang/src/github.com/GoBelieveIO/im_service/im”
make: *** [im_bin] 错误 2

**Comment by richmonkey** [comment]
下载的版本不对， dep ensure会选择正确的版本

**Comment by daibou007** [comment]
可以指定代理，把依赖转到国内，https://goproxy.io/zh/
