### ISSUE TITLE
单聊消息同步问题

### ISSUE THREAD

**Issue by M6ZeroG** [GoBelieveIO/im_service#48]
注意到在IM实例处理client发来的 `MSG_IM`时会同时投递 `MSG_IM` 和 `MSG_SYNC_NOTIFY` 至接收方和client其他登陆点，目的似乎是为了保证各消息接收点的消息时序一致性，在这里既发送`MSG_IM` 又发送 `MSG_SYNC_NOTIFY`的方式是否显得冗余：
1、IM实例处理 MSG_IM 时是否可以仅发送MSG_IM，让接收消息的终端自己根据msgid判断是否向服务器同步消息
2、IM实例处理 MSG_IM 时是否可以仅发送MSG_SYNC_NOTIFY，让接收消息的终端自己主动向服务器拉取具体消息
这样似乎可以减少服务器处理消息的压力，请教
https://github.com/GoBelieveIO/im_service/blob/f8a46c7aaa1e24e7de4b79eba1724f91fa71f581/im/peer_client.go#L205-L216

**Comment by richmonkey** [comment]
是有冗余的问题，可以把这两个消息内容合二为一，不过就会出现兼容性问题，所以当前发送两个消息，大部分情况下MSG_SYNC_NOTIFY是多余的。
