### ISSUE TITLE
The package github.com/jimlawless/cfg is not found!!

### ISSUE THREAD

**Issue by kellerli** [GoBelieveIO/im_service#5]
config.go:25:8: cannot find package "github.com/jimlawless/cfg" 
the package github.com/jimlawless/cfg is not found!!

**Comment by richmonkey** [comment]
Please go get xxx manually

**Comment by kellerli** [comment]
the package github.com/jimlawless/cfg has been removed by author

**Comment by richmonkey** [comment]
Please pull the latest code.
