### ISSUE TITLE
请教大神几个问题

### ISSUE THREAD

**Issue by zkbqhuang** [GoBelieveIO/im_service#50]
1）im，imr，ims，lru几个目录简单说明，从名字不容易看出来
2）im_sevice目录下的多个文件，与im，imr，ims目录里面都有重复的，为什么不放进去？
3）还继续更新吗？

**Comment by richmonkey** [comment]
在维护。工程结构，目录命名只是一种做法，当然不一定是最好的。目录文件重复是因为历史原因造成的。
