### ISSUE TITLE
重复消息

### ISSUE THREAD

**Issue by tyz-coder** [GoBelieveIO/im_service#53]
安卓客户端偶尔发送连续重复消息，但是前端只显示一条，后端会收到多条一样的消息落库

**Comment by tyz-coder** [comment]
> 安卓客户端偶尔发送连续重复消息，但是前端只显示一条，后端会收到多条一样的消息落库
> `
> func (client *Client) HandleMessage(msg *Message) {
> 
> ```
> log.Info("msg cmd:", Command(msg.cmd))
> 
> fmt.Println("新的消息 msg cmd:", Command(msg.cmd), msg.body)
> 
> ......
> ```
> 
> }
> `
> 
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}
> > 新的消息 msg cmd: MSG_PING 
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}

**Comment by tyz-coder** [comment]
> 安卓客户端偶尔发送连续重复消息，但是前端只显示一条，后端会收到多条一样的消息落库
> `
> func (client *Client) HandleMessage(msg *Message) {
> 
> ```
> log.Info("msg cmd:", Command(msg.cmd))
> 
> fmt.Println("新的消息 msg cmd:", Command(msg.cmd), msg.body)
> 
> ......
> ```
> 
> }
> `
> 
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}
> > 新的消息 msg cmd: MSG_PING 
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}
> > 新的消息 msg cmd: MSG_IM &{79559 79575 1620461680 0 {"text":"kkkkk","uuid":"0b5139f0-4f3a-4adb-9f44-e11a6882fa59"}}

**Comment by richmonkey** [comment]
这是正常现象， 前端没有显示重复的消息，只是前端去重了

**Comment by tyz-coder** [comment]
> 这是正常现象，前端没有显示重复的消息，只是前端去重了

那离线消息推送怎么去重呢？

**Comment by richmonkey** [comment]
1. 客户端不要发送重复的消息
2. 推送脚本自己去重， 类似客户端的做法
