### ISSUE TITLE
message seq problem

### ISSUE THREAD

**Issue by morya** [GoBelieveIO/im_service#8]
message seq is inited in the below function, it's not global variable, and I don't see any function loading this one, so, when one client is offline and online again, the seq will always begin from 0?
```
func (client *Client) Write() {
```

我在上面的函数里面看到有初始化seq的地方，但没有看到任何地方对它进行持久化，那么，客户端再次连接进来之后，seq岂不是依然从0开始？

看文档不是这么说的，文档说客户端连接后，可以从某个seq位置来取消息，类似于断点续传？

**Comment by richmonkey** [comment]
这个seq支持用户ack时的标识，所以只要单个链接唯一就好了。
消息的持久化以及离线消息的获取使用EMessage结构里面的msgid去判别的，同时每个用户接受到的最后一条消息的id是存储在storage server里面的

**Comment by morya** [comment]
谢谢，感觉工程使用makefile来区分不同的模块，所有文件都放置在一个目录，有些混乱。
建议类似于nsq的internal文件夹或者codis-proxy的 pkg/xx 方式组织。
